#!/bin/sh

function usage(){
    echo "Usage: apollo <command>";
    echo "";
    echo "Commands:";
    echo "";
    echo "release: builds in release mode (minimized javascript)";
    echo "deploy:  builds unoptimized war file (no processing of javascript)";
    echo "run:     runs from current directory debug mode (non-minimized javascript)";
    echo "debug:   runs from current directory in debug mode (non-minimized javascript)";
    echo "clean:   removes any existing jbrowse builds from build directory";
    echo "help:    this message";
};

if [[ $# == 0 || $1 == help || $1 == --help ]]; then
   usage
fi

if [ ! -e "./config.xml" ]; then
   echo "No config.xml found, exiting."
   echo "You must copy and sample_config.xml to config.xml in order to build."
   exit 1;
fi

if [ ! -e "./config.properties" ]; then
   echo "No config.properties found, exiting."
   echo "You must copy and sample_config.properties to config.properties in order to build."
   exit 1;
fi

if [[ $1 == "run" ]];then
    # should call the copy target first
    mvn tomcat7:run
fi

if [[ $1 == "debug" ]];then
    # TODO: feel like there is a better way to do this
    OLD_MAVEN_OPTS=$MAVEN_OPTS
    export MAVEN_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
    mvn tomcat7:run
    export MAVEN_OPTS=$OLD_MAVEN_OPTS
    unset OLD_MAVEN_OPTS
fi

if [[ $1 == "release" ]];then
    # should call the copy target first
    mvn tomcat7:run
fi

if [[ $1 == "deploy" ]];then
    # should call the copy target first
    mvn package
fi


if [[ $1 == "clean" ]];then
    # should call the copy target first
    mvn clean
fi
