#!/bin/bash
APOLLO_ROOT_DIRECTORY=`pwd`
APOLLO_BUILD_DIRECTORY=$APOLLO_ROOT_DIRECTORY
APOLLO_WEBAPP_DIRECTORY="$APOLLO_ROOT_DIRECTORY/web-app"
APOLLO_JBROWSE_DIRECTORY="$APOLLO_WEBAPP_DIRECTORY/jbrowse"
APOLLO_JBROWSE_GITHUB="$APOLLO_ROOT_DIRECTORY/jbrowse-github"
grails clean
#remove jbrowse github if "clean.sh all"
if [[ $1 == all ]]; then
  rm -rf "$APOLLO_JBROWSE_DIRECTORY"
  rm -rf "$APOLLO_JBROWSE_GITHUB"
fi
