#!/bin/sh
: ${APOLLO_ROOT_DIRECTORY:=`pwd`}
: ${APOLLO_WEBAPP_DIRECTORY:="$APOLLO_ROOT_DIRECTORY/src/main/webapp"}
: ${APOLLO_JBROWSE_DIRECTORY:="$APOLLO_WEBAPP_DIRECTORY/jbrowse"}
rm -rf $APOLLO_JBROWSE_DIRECTORY/plugins/WebApollo
cp -r $APOLLO_ROOT_DIRECTORY/client/apollo $APOLLO_JBROWSE_DIRECTORY/plugins/WebApollo
