<#--package org.gmod.gbol.simpleObject.${pojo.getMetaAsString("chadoModule")};-->
package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.${pojo.getDeclarationName()}.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class ${pojo.getDeclarationName()} extends org.gmod.gbol.simpleObject.generated.Abstract${pojo.getDeclarationName()} {

	private static final long serialVersionUID = 1L;

	public ${pojo.getDeclarationName()}(){
		super();
	}
}
