/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by hbm2java", 0)}
 */
<#include "Ejb3TypeDeclaration.ftl"/>
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} Abstract${pojo.getDeclarationName()} extends AbstractSimpleObject ${pojo.getImplementsDeclaration()}