package org.bbop.apollo

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                // validate everyone right now
                return  true

                // Ignore direct views (e.g. the default main index page).
//                if (!controllerName) return true
//
//                // Access control by convention.
//                accessControl()
            }
        }
    }
}
