package org.bbop.apollo

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                log.debug "apollo filter ${controllerName}::${actionName}"
//                accessControl()
            }
        }
    }
}
