name: Python-Apollo

#on: ["push", "pull_request"]
on: ["push"]

jobs:
  test-python-apollo:
    name: test-python-apollo

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.7]
    steps:
      - name: Checkout Apollo
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Apollo
        run: ./grailsw run-app &
      - name: Setup pytyhon
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout Pypi
        uses: actions/checkout@v2
        with:
          repository: galaxy-genome-annotation/python-apollo
          path: python-apollo
          ref: master
      - name: Python install
        run: |
          cd python-apollo
          pip install -U pip setuptools nose
          python setup.py install
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Sleep until Apollo is built
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      - name: Bootstrap
        run: |
          export ARROW_GLOBAL_CONFIG_PATH=`pwd`/test-data/local-apollo2-arrow.yml
          cd python-apollo
          ./bootstrap_apollo.sh --nodocker
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
        run: |
          export ARROW_GLOBAL_CONFIG_PATH=`pwd`/test-data/local-apollo2-arrow.yml
          cd python-apollo
          python setup.py nosetests



