package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.CV.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class CV extends org.gmod.gbol.simpleObject.generated.AbstractCV {

	private static final long serialVersionUID = 1L;

	public CV(){
		super();
	}
	
	public CV(String cvName){
		super(cvName);
	}


	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return new SimpleObjectIterator(this);
	}

	private static class SimpleObjectIterator extends AbstractSimpleObjectIterator
	{

		private static class Status extends AbstractSimpleObjectIterator.Status
		{
			public static final int done = 1;
		}
		
		public SimpleObjectIterator(CV cv)
		{
			super(cv);
		}
		
		public AbstractSimpleObject next()
		{
			AbstractSimpleObject retVal = null;
			if (status == Status.notSet) {
				retVal = peek();
				status = Status.done;
			}
			current = retVal;
			return retVal;
		}
	}
}
