package org.gmod.gbol.simpleObject;

import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.ElementResult.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class ElementResult extends org.gmod.gbol.simpleObject.generated.AbstractElementResult {

	private static final long serialVersionUID = 1L;

	public ElementResult(){
		super();
	}

//	@Override
//	public Collection<AbstractSimpleObject> getWriteObjects() {
//		// TODO Auto-generated method stub
//		return null;
//	}

	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return null;
	}

}
