package org.gmod.gbol.simpleObject;

import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureDBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureDBXref extends org.gmod.gbol.simpleObject.generated.AbstractFeatureDBXref {

	private static final long serialVersionUID = 1L;

	public FeatureDBXref(){
		super();
	}
	
	public FeatureDBXref(FeatureDBXref src) {
		this(src.getFeature(), src.getDbxref(), src.isIsCurrent());
	}
	
	public FeatureDBXref(Feature feature, DBXref dbxref, boolean isCurrent) {
		setFeature(feature);
		setDbxref(dbxref);
		setIsCurrent(isCurrent);
	}

//	@Override
//	public Collection<AbstractSimpleObject> getWriteObjects() {
//		// TODO Auto-generated method stub
//		return null;
//	}

	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return null;
	}

}
