package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureCVTermPublication.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureCVTermPublication extends org.gmod.gbol.simpleObject.generated.AbstractFeatureCVTermPublication {

	private static final long serialVersionUID = 1L;

	public FeatureCVTermPublication(){
		super();
	}

//	@Override
//	public Collection<AbstractSimpleObject> getWriteObjects() {
//		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
//		// Have to write yourself
//		writeObjects.add(this);
//		
//		// Singletons
//		writeObjects.addAll(this.getPublication().getWriteObjects());
//		
//		return writeObjects;
//	}

	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return new SimpleObjectIterator(this);
	}

	private static class SimpleObjectIterator extends AbstractSimpleObjectIterator
	{

		private static class Status extends AbstractSimpleObjectIterator.Status
		{
			public final static int pub = 1;
		}
	
		public SimpleObjectIterator(FeatureCVTermPublication featureCvtermPub)
		{
			super(featureCvtermPub);
		}
		
		public AbstractSimpleObject next()
		{
			FeatureCVTermPublication featureCvtermPub = (FeatureCVTermPublication)object;
			AbstractSimpleObject retVal = null;
			if (status == Status.self) {
				retVal = peek();
				processSingletonIterator(Status.pub, featureCvtermPub.getPublication());
			}
			else {
				if (status == Status.pub) {
					retVal = soIter.next();
				}
			}
			current = retVal;
			return retVal;
		}
	}
	
}
