package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeaturePublication.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeaturePublication extends org.gmod.gbol.simpleObject.generated.AbstractFeaturePublication {

	private static final long serialVersionUID = 1L;

	public FeaturePublication(){
		super();
	}

//	@Override
//	public Collection<AbstractSimpleObject> getWriteObjects() {
//		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
//		// Have to write yourself
//		writeObjects.add(this);
//		
//		// Singletons
//		writeObjects.addAll(this.getPublication().getWriteObjects());
//		
//		// Multiples
//		for (FeaturePublicationProperty fpp : this.getFeaturePublicationProperties())
//			writeObjects.addAll(fpp.getWriteObjects());
//		
//		return writeObjects;
//	}

	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return new SimpleObjectIterator(this);
	}

	private static class SimpleObjectIterator extends AbstractSimpleObjectIterator
	{
		private static class Status extends AbstractSimpleObjectIterator.Status
		{
			public static final int pub = 1;
			public static final int featurePubProps = 2;
		}
		
		public SimpleObjectIterator(FeaturePublication featurePub)
		{
			super(featurePub);
		}

		public AbstractSimpleObject next()
		{
			FeaturePublication featurePub = (FeaturePublication)object;
			AbstractSimpleObject retVal = null;
			if (status == Status.self) {
				retVal = peek();
				processSingletonIterator(Status.pub, featurePub.getPublication());
			}
			else {
				retVal = soIter.next();
				if (status == Status.pub) {
					processCollectionIterators(Status.featurePubProps,
							featurePub.getFeaturePublicationProperties());
				}
				if (status == Status.featurePubProps) {
					processLastCollectionIterator();
				}
			}
			current = retVal;
			return retVal;
		}
	}
	
}
