package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureRelationshipPropertyPublication.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureRelationshipPropertyPublication extends org.gmod.gbol.simpleObject.generated.AbstractFeatureRelationshipPropertyPublication {

	private static final long serialVersionUID = 1L;

	public FeatureRelationshipPropertyPublication(){
		super();
	}

	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return new SimpleObjectIterator(this);
	}

	private static class SimpleObjectIterator extends AbstractSimpleObjectIterator
	{

		private static class Status extends AbstractSimpleObjectIterator.Status
		{
			public final static int pub = 1;
		}
	
		public SimpleObjectIterator(FeatureRelationshipPropertyPublication featureRelationshipPropPub)
		{
			super(featureRelationshipPropPub);
		}
		
		public AbstractSimpleObject next()
		{
			FeatureRelationshipPropertyPublication featureRelationshipPropPub =
				(FeatureRelationshipPropertyPublication)object;
			AbstractSimpleObject retVal = null;
			if (status != Status.self) {
				retVal = soIter.next();
				if (status == Status.notSet) {
					processSingletonIterator(Status.pub, featureRelationshipPropPub.getPublication());
				}
				if (status == Status.pub) {
					AbstractSimpleObject newClone = processLastSingletonIterator();
					((FeatureRelationshipPropertyPublication)clone).setPublication((Publication) newClone);
				}
			} else {
				retVal = peek();
				status = Status.done;
			}
			current = retVal;
			return retVal;
		}
	}
	
}
