package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PhenotypeStatement.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PhenotypeStatement extends org.gmod.gbol.simpleObject.generated.AbstractPhenotypeStatement {

	private static final long serialVersionUID = 1L;

	public PhenotypeStatement(){
		super();
	}

//	@Override
//	public Collection<AbstractSimpleObject> getWriteObjects() {
//		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
//		// Have to write yourself
//		writeObjects.add(this);
//		
//		// Singletons
//		writeObjects.addAll(this.getEnvironment().getWriteObjects());
//		writeObjects.addAll(this.getType().getWriteObjects());
//		writeObjects.addAll(this.getPublication().getWriteObjects());
//		writeObjects.addAll(this.getPhenotype().getWriteObjects());
//		writeObjects.addAll(this.getGenotype().getWriteObjects());
//		
//		return writeObjects;
//	}

	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return null;
	}

}
