package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PhenotypeCVTerm.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PhenotypeCVTerm extends org.gmod.gbol.simpleObject.generated.AbstractPhenotypeCVTerm {

	private static final long serialVersionUID = 1L;

	public PhenotypeCVTerm(){
		super();
	}

//	@Override
//	public Collection<AbstractSimpleObject> getWriteObjects() {
//		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
//		// Have to write yourself
//		writeObjects.add(this);
//		
//		// Singletons
//		writeObjects.addAll(this.getCvterm().getWriteObjects());
//		
//		return writeObjects;
//	}

	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return new SimpleObjectIterator(this);
	}

	private static class SimpleObjectIterator extends AbstractSimpleObjectIterator
	{

		private static class Status extends AbstractSimpleObjectIterator.Status
		{
			public final static int cvterm = 1;
		}
	
		public SimpleObjectIterator(PhenotypeCVTerm phenotypeCvterm)
		{
			super(phenotypeCvterm);
		}
		
		public AbstractSimpleObject next()
		{
			PhenotypeCVTerm phenotypeCvterm = (PhenotypeCVTerm)object;
			AbstractSimpleObject retVal = null;
			if (status == Status.self) {
				retVal = peek();
				status = Status.cvterm;
				soIter = phenotypeCvterm.getCvterm().getWriteableObjects();
			}
			else {
				if (status == Status.cvterm) {
					retVal = soIter.next();
				}
			}
			current = retVal;
			return retVal;
		}
	}
	
}
